### ISSUE TITLE
Parallel stream support

### ISSUE THREAD

**Issue by ggam** [eclipse/microprofile-context-propagation#10]
I've just filled this issue on the Concurrency Utilities spec (https://github.com/eclipse-ee4j/concurrency-api/issues/46), but I think this is the best place to start this discussion right now.

---

Parallel streams run on the common fork join pool and that can't be changed but with hacks (https://www.baeldung.com/java-8-parallel-streams-custom-threadpool). However, the ThreadFactory of the common thread pool can be specified with the java.util.concurrent.ForkJoinPool.common.threadFactory system property.

Implementations of this spec could use that to propagate application context to the common thread pool, taking care of doing it only during application processing.

As a bonus, that server-installed thread factory should allow delegation to a user provided one. A common usecase for that is to get metrics about submitted tasks.

**Comment by ggam** [comment]
> Also note that ForkJoinWorkerThread does not appear to provide any hooks by which the ForkJoinPool could notify it of the boundary between the thread being used to run one task vs another.

You're right, that makes my original proposal useless. What can be done is creating a `ManagedForkJoinPool` that captures the original context of the calling thread and uses proxies for it within task execution (I imagine that's the same it does now with e.g. `ManagedExecutorService`), although it can be tricky for the same reason you described above.

But I don't think ForkJoinPoool is much used today anyway. It would probably suffice to provide a way to propagate context to parallel streams. Something like:
```
new ManagedStream(myList.stream()).
    parallel().
    map(...)
    ....;
```
Streams returned from the runtime (e.g. JPA `getResultStream()`) should always returned managed streams that are safe to parallelize. The underlying `ForkJoinPool` would be crafted to capture context and propagate context at the beginning of each task and removing it at the end, in some vendor specific way.

Do you think that approach is feasible?

**Comment by njr-11** [comment]
While the approach might be feasible in some respects, I worry about the performance of establishing and removing context with every stream operation.  Ideally, a user would want to contextualize only the specific operations where they actually need to rely on context, and even then would only care about parallel streams, not sequential ones running on the same thread where context is already available.

To some extent, the methods being added to MicroProfile Concurrency's ThreadContext API will already make some of this possible.  For example,

```
itemStream.parallel()
          .map(item -> item.getProductId())
          .map(threadCtx.withCurrentContext(id -> {
              result = ... computation that requires thread context
              return result;
          }))
          ...
```

ThreadContext currently covers Function, BiFunction, Consumer, BiConsumer, and a few others.  There is some overlap of these with stream operations.  If this approach seems reasonable, which other operations do you see being useful to contextualize?

Also, it should be noted that for generic cases, you can even create a multiple-use context snapshot, which could be used as follows,

```
Executor contextSnapshot = threadCtx.currentContextExecutor();

itemStream.parallel()
          .map(item -> item.getProductId())
          .map(id -> {
              ... do stuff that doesn't need context
              contextSnaphot.execute(() -> {
                  ... now do something that requires context
              };
              return result;
          })
          ...
```

**Comment by njr-11** [comment]
Planning to close this unless any concerns are raised that the above solution is not adequate.

**Comment by ggam** [comment]
@njr-11 I'm fine with it, thanks
