### ISSUE TITLE
Rename specification to reflect it's purpose

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-context-propagation#142]
I'd like to propose renaming the specification to "MP Context Propagation".

Such a name fits better with what the specification actually defines, and removes confusion and comparison with the EE Concurrency specification.

**Comment by manovotn** [comment]
+1
This sounds like a sensible follow-up step on what we did in #133 (spec tweaks to encourage various different scenarios, disjoining the spec from EE Conc-oriented approach).

**Comment by njr-11** [comment]
Under #133, language was softened, such that while we continue to state that full compatibility is maintained with EE Concurrency, there are no longer direct claims within the MP Concurrency specification as to what the future direction of EE Concurrency ought to be.  The updates were not about distancing ourselves from EE Concurrency, but rather our avoidance of overstepping our bounds in saying what EE Concurrency ought to do, and in adding additional examples that highlight MP Concurrency-specific features such as our contextualizing proxies for the Java SE Concurrency CompletionStage and CompletableFuture.

While I don't find the alternative name problematic, I would argue the current name is also very indicative of what the spec is about and I don't really see a benefit to changing it at this point.

The MP Concurrency spec continues to center around providing reliable thread context when using the following interfaces from Java SE Concurrency:
java.util.concurrent.CompletionStage
java.util.concurrent.CompletableFuture
java.util.concurrent.ExecutorService

Even the ThreadContext interface is written to contextualize java.util.concurrent.CompletionStage and java.util.concurrent.CompletableFuture and the exact set of functional interfaces that are supplied as lambdas to java.util.concurrent.CompletionStage and java.util.concurrent.CompletableFuture and java.util.concurrent.ExecutorService.  The only other capability of ThreadContext is to create a java.util.concurrent.Executor that applies context snapshots, again based on a Java SE Concurrency interface.
ManagedExecutor, of course, is just as completely tied to Java SE Concurrency.

While it can be argued that Java SE Concurrency may not have the best name, it is a well-known and widely adopted standard, and our current name makes sense given our alignment with it.

**Comment by kenfinnigan** [comment]
From my perspective, the fact we're not providing any Concurrency related implementations, such as `CompletionStage`, means we shouldn't be calling it "Concurrency". It is misleading and causes confusion with other concurrency specification initiatives. Even with the spec wording being softened, the name itself causes confusion.

Calling it "Concurrency" because it integrates with other concurrency specifications doesn't really justify the name.

You've even mentioned in your comment that this spec is about reliable context when using Java SE Concurrency. We're not providing additional Concurrency mechanisms. It's about propagation of context.

**Comment by dmlloyd** [comment]
FWIW "Java SE Concurrency" isn't a thing.  There's no spec with that name, and any perceived alignment between such a thing and "Java EE Concurrency" is therefore non-existent.  JSR 166 is entitled "Concurrency Utilities", a clearly utilitarian identifier, and certainly doesn't seem to denote any particular method of naming in this regard.

Furthermore `CompletionStage` is as much associated with reactivity as it is with JSR 166 these days, and it's clear which way the wind is blowing.  The term "Concurrency" from a specification perspective seems obsolete in this light, as it conflates asynchronicity with reactivity (two very different things).  Context propagation on the other hand applies equally to both, thus it seems to be a better name.

**Comment by njr-11** [comment]
> We're not providing additional Concurrency mechanisms. It's about propagation of context.

The first part of this statement isn't accurate.  Implementations of the spec do provide implementations of the following:
java.util.concurrent.CompletionStage
java.util.concurrent.CompletableFuture
java.util.concurrent.ExecutorService
java.util.concurrent.Executor

Some implementations might borrow from existing infrastructure in java.util.concurrent (and elsewhere) to accomplish that, however, it doesn't change the fact that users are getting java.util.concurrent package interfaces from this spec.

**Comment by aguibert** [comment]
Version 1.0 of this spec provides 2 key things:

1. Configurable Executors, via `org.eclipse.microprofile.concurrent.ManagedExecutor`. Properties like `maxAsync` to limit concurrent work and `maxQueued` to limit the work backlog. 
2. Context propagation

Use case (1) hasn't received much attention because it's straightforward and there have been no disagreements about it, but it was one of the reasons this spec was created (for usage by MP Fault Tolerance's `@Bulkhead` anno).

Context propagation has received a lot of attention in this spec, but it's certainly not the only reason we have this spec. For this reason, I think "MP Concurrency" is still a fitting name.

**Comment by kenfinnigan** [comment]
@njr-11 I wouldn't consider implementations that wrap the existing functionality, and then add context propagation, to be saying the spec provides "new" concurrency functionality.

@aguibert to see there have been no disagreements about (1) is inaccurate, as I'm pretty sure there were plenty around setting the defaults.

In terms of use case being added to support MP FT usage in `@Builkhead`. It may as well be removed from the spec because MP FT can't use this spec for the foreseeable future. Until such time as this spec is in the full platform, which I don't see good arguments to include it at present, then MP FT is unable to use it within any release that wants to be part of the MP platform.

**Comment by njr-11** [comment]
> @njr-11 I wouldn't consider implementations that wrap the existing functionality, and then add context propagation, to be saying the spec provides "new" concurrency functionality.

Assuming that is even possible, it would be an implementation detail of one particular implementation which figured out how to do so in a valid way.  Speaking for our own implementation, while we do borrow from Java SE Concurrency in some places where that was possible, it is not a simple wrapper as you are suggesting. We just didn't see any way for that to be possible.

> In terms of use case being added to support MP FT usage in `@Builkhead`. It may as well be removed from the spec

To clarify, while this could be used for Bulkhead, Bulkhead wasn't actually the requirement from MP FaultTolerance that drove creation of this spec.  Rather it was MP FaultTolerance's `@Asynchronous` methods, which return java.util.concurrent.Future, and MP FaultTolerance wanted to expand that to java.util.concurrent.CompletableFuture and have a better way of obtaining a CompletableFuture than from Java SE Concurrency.

**Comment by aguibert** [comment]
@kenfinnigan we may have discussed maxAsync/maxQueued at some point (all I can recall is discussing defaults in general). Also, whether or not this spec gets included in the MP platform is unrelated to naming. 

However, these things are beside the point. The point I was trying to make is that this spec does more than just context propagation, so I think "MP Context Propagation" would be an inaccurate name, so I am opposed to it. Until I see a more fitting name than what we currently have, I don't see any reason to change.

**Comment by kenfinnigan** [comment]
From my, and several others at Red Hat, perspective we consider "MP Concurrency" to be an inaccurate name.

@njr-11 whatever the particular use case from MP FT my point stands. They are not able to use anything from this specification for the foreseeable future.

**Comment by njr-11** [comment]
> @njr-11 whatever the particular use case from MP FT my point stands. They are not able to use anything from this specification for the foreseeable future.

We may have missed MicroProfile 2.2, but if we can come to agreement on a name that is agreeable, I don't see any reason why we can't put out an independent release and then aim for inclusion in MicroProfile 2.3, which has been our target plan all along.  Users of MP FaultTolerance will immediately be able to start using MP Concurrency (or whatever we call it) in combination with the MP 2.2 release with the FaultTolerance `@Asynchronous` signature that allows for returning java.util.concurrent.CompletionStage.  The interfaces are all there, the MP FaultTolerance spec will just need an update to wording pointing out that you can get these completion stages via MP Concurrency, but there will be nothing preventing users from doing that prior to the addition of this wording.  MP 2.2 is targetted for June if I remember correctly, and that is very much the foreseeable future.

**Comment by kenfinnigan** [comment]
@njr-11, once there is an independent release of this spec then it can be considered for inclusion in an MP platform release. But, inclusion in the MP platform is not a given. There are already concerns it's becoming too large even before this spec is considered.

The next scheduled platform release is MP 3.0 in June, and I don't see this spec being included in that platform release. There just isn't enough time to get feedback and comments on a first release to warrant inclusion in the platform for June.

With respect to the spec being more than context propagation, it's hard to see that when the opening line of the spec says "MicroProfile Concurrency introduces APIs for propagating contexts across units of work that are thread-agnostic".

**Comment by njr-11** [comment]
I agree that inclusion into the MP platform is not a given. We can only aim to put our spec into the right position (independent release) where it can be fairly considered.

> With respect to the spec being more than context propagation, it's hard to see that when the opening line of the spec says "MicroProfile Concurrency introduces APIs for propagating contexts across units of work that are thread-agnostic".

That's only because Stephane just changed it to that under #133.  We didn't understand that to be part of a push to switch the intent of the spec.

**Comment by jclingan** [comment]
When I see "MP Concurrency", I immediately think that this spec is related to Java EE concurrency. Check the Live Hangout (recording and/or meeting minutes), where I was corrected for assuming that this spec would pull Java EE concurrency into MicroProfile. I will not be alone in being confused, not by a long shot. I do have to ask though - does this imply a spec name change only or a spec + namespace name change?

When it comes to MP FT relying on this standalone spec, I think that is a non-starter in spec language because a core spec can't require on a non-core spec.  However, it can be used as a implementation detail that doesn't tie other implementations to this spec. BTW, I am using this as example input to a proposal about platform specs and release processes. It's just taking longer than I thought.

**Comment by kwsutter** [comment]
@jclingan brings up a good point...  Are you only asking to change the name of the spec and not the package name?  If this ripples to the package name, then this is a kind of a major change that shouldn't have been introduced at the 11th hour...  On the other hand, if this proposal doesn't affect the package name, then why change the name of the spec?  Catch-22.

Although there is some confusion about the relationship between MP Concurrency and the Concurrency Utilities for Java EE (note that this is the real name of the Java EE spec), the term "concurrency" is generic enough to be used in multiple contexts.  Even with the re-wording of the first, introductory paragraph of the spec, I still think that MP Concurrency sounds appropriate and easier to understand.  I know from talking with @njr-11 and @aguibert, it has been a goal to extend the capabilities of the Concurrency Utilities for Java EE with this spec without conflicting with it.  So, providing some type of linkage via the name is fine with me.  I think it better represents the "end game" for the spec.

**Comment by kenfinnigan** [comment]
I hadn't thought beyond the spec name itself, as that is the bit that most people see first and foremost.

I wouldn't consider it the 11th hour. I say that because I'm aware that the engineers from Red Hat that have been working on this specification agreed to an RC release on the proviso that the APIs can be changed. Red Hat is not convinced the proposed APIs are appropriate, and we wanted the time to "test them out" with users before an RC is released. This was dismissed by IBM because a full release was needed for inclusion in OpenLiberty.

As such an agreement was reached whereby an RC could be done on the agreement that the APIs can change and not have to wait for another major version.

I, and others, at Red Hat have concerns that this specification is poorly named, hence the desire to change it before an RC is cut.

I'm not sure of the "end game" you refer, as I'm not sure what extending of the Concurrency Utilities for Java EE can be done without significant encroachment into the realm of JakartaEE, or the JDK.

**Comment by manovotn** [comment]
> @jclingan brings up a good point... Are you only asking to change the name of the spec and not the package name? If this ripples to the package name, then this is a kind of a major change that shouldn't have been introduced at the 11th hour... On the other hand, if this proposal doesn't affect the package name, then why change the name of the spec? Catch-22.

This is hardly an 11th hour. We haven't had any release, not even CR. Plus there was recently a discussion on a CR on condition that it doesn't prevent us from making breaking changes.
Hence, can still effect any breaking changes we choose to.

If we were to change the name, changing packages does sound appropriate to me.

> 
>  I think it better represents the "end game" for the spec.

Throughout the making of this spec, we have bumped into this many times over. The "end game", as you call it, has different meaning for both parties. E.g. concurrent (as in parallel) versus reactive perception. However, we both actually operate on **context propagation** and that's the crux of this specification. Having a name derived from that seems not only natural but also fair to both parties as it doesn't promote either perception/approach.

**Comment by Emily-Jiang** [comment]
Reactive programming is popular. CompletionStage usage is on the rise. Hence the existence of this spec. At the moment, this spec provides two major functionalities pointed out by Andy and Nathan Config executor; context propagation. Renaming to context propagation will limit this spec and inaccurate. I think this spec should cover all potential issues in concurrency or asynchronous. Recently Gavin King asked to move Asynchronous annotation to this spec. This spec is not just context propagation but to provide solutions when using reactive programming. I see it has huge room to grow. Concurrency pretty much says what’s in the tin.

**Comment by manovotn** [comment]
> Renaming to context propagation will limit this spec

You could likewise argue that current name limits the specification by enforcing association with EE conc (up to the point where people assume it depends on it). Name itself hardly limits it, looks at CDI, how does that limit it from implementing interception and event models?

> I think this spec should cover all potential issues in concurrency or asynchronous. Recently Gavin King asked to move Asynchronous annotation to this spec. This spec is not just context propagation but to provide solutions when using reactive programming. I see it has huge room to grow.

We cannot fathom what will end up in the specification should it grow rapidly. However, we can reflect what it currently does and what we designed it for initially. And that is context propagation since the two main constructs we have (`ManagedExecutor`, `ThreadContext`) are all about that. If you just wanted an executor, you don't need this spec for it.

**Comment by njr-11** [comment]
> and we wanted the time to "test them out" with users before an RC is released. This was dismissed by IBM because a full release was needed for inclusion in OpenLiberty.

This is not a truthful representation of what I asked for in requesting a release candidate.  In fact, the recent OpenLiberty betas already include the MicroProfile Concurrency spec and an implementation that passes all of the TCK tests.  I very clearly stated that our purpose in asking for a release candidate is because many users are unwilling to test out any new spec until there is a release candidate.  While true that OpenLiberty cannot promote it from beta to GA until a full release occurs, we have never used that as an argument for pushing the progress of this spec, nor have we dismissed anything on that basis.  Our goal here is the same as yours: to let users start testing out the spec.  We see having a release candidate as the best way to make that happen.  When I opened the issue to create the release candidate, there were no open issues remaining against the v1.0 release of the spec.  Now there is this issue, and we have halted progress on the initial release candidate because of it.

**Comment by kenfinnigan** [comment]
Apologies @kwsutter, I'd only been told that IBM required an RC release for OpenLiberty. Not the additional detail you provided.

For me this also gets to the original goal of MicroProfile, in that we're creating specifications based on existing implementations. ie. we take an implementation first approach.

Though to date it's usually been more a "just in time" implementation for a specification, I'd prefer we get back to the original goal of creating a specification from something that already works.

That is one of the reasons why I prefer we don't do an RC for this specification until we're comfortable with what has been defined in terms of an API is what users actually want. Why can't OpenLiberty and SmallRye implementations embed the API code within their implementation to get community feedback before we commit to an API?

@Emily-Jiang, I wasn't aware that the goal of this specification was to provide solutions for reactive programming. Aren't the reactive specific specifications developed for that purpose?

**Comment by kwsutter** [comment]
@kenfinnigan and @Emily-Jiang, I agree that we shouldn't confuse this issue with the need for a "MP reactive strategy"...  Sure, there may be aspects of MP Concurrency that may be usable by Reactive, but let's keep these two efforts separate.  At least until we make progress on the MP Reactive Strategy...

**Comment by njr-11** [comment]
> If we were to change the name, changing packages does sound appropriate to me.

I agree with this.  If we rename the spec, then the packages, class names, git repo, spec doc and everything else in the spec must change to line up with it.  It would be nonsensical to have a spec called MicroProfile Context Propagation that has all of its user-facing API classes in a package named org.eclipse.microprofile.concurrent in a github repo named github.com/eclipse/microprofile-concurrency, where the spec implementer supplies a "ConcurrencyProvider" class, and so forth.

For this discussion maybe it would help to envision what the packages/API/class names would look like corresponding to a MicroProfile Context Propagation spec name.  Here is an example of that (using my best guesses of how it might change),

git repo:
`github.com/eclipse/microprofile-context`

API:
```
org.eclipse.microprofile.context.ThreadContext
org.eclipse.microprofile.context.ManagedExecutor
```

SPI:
```
org.eclipse.microprofile.context.spi.ContextManager  (from ConcurrencyManager)
org.eclipse.microprofile.context.spi.ContextManagerProvider (from ConcurrencyProvider)
org.eclipse.microprofile.context.spi.ThreadContextProvider
...
```

I doubt this will reverse anyone's preference for the spec name, but I want to at least be clear on the sort of thing we will be getting if the spec name changes.

**Comment by njr-11** [comment]
After an offline conversation with Kevin on this, we have concluded that is not in the best interest of users to continue discussion over the specification name, delaying progress on the release candidate that users want to see before they start really using the spec. For that reason, we will be accepting this name change to allow for continued progress.
