### ISSUE TITLE
TCK bug in `ThreadContextText.unchangedContextListDefaultsToEmpty()`?

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-context-propagation#152]
We have this test fail for us because the TCK has an mp-config file of:

```
ThreadContext/cleared=Buffer
ThreadContext/propagated=
ThreadContext/unchanged=Remaining
```

and the test does:

```java
        ThreadContext labelContext = ThreadContext.builder()
                .propagated(Label.CONTEXT_NAME)
                .cleared(ThreadContext.ALL_REMAINING)
                .build();
```

So it does not set the `unchanged` set, which defaults to `Remaining`, and our implementation throws an exception because `Remaining` cannot be in two sets (cleared and unchanged).

I think our implementation is right, no?

**Comment by njr-11** [comment]
The microprofile-config.properties file applies only to the MPConfigTest test application. It is added here,
```
        return ShrinkWrap.create(WebArchive.class, MPConfigTest.class.getSimpleName() + ".war")
                .addClass(MPConfigBean.class)
                .addClass(MPConfigTest.class)
                .addAsManifestResource("META-INF/microprofile-config.properties", "microprofile-config.properties")
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml")
                .addAsLibraries(fakeContextProviders);
```

It does _not_ apply to the ThreadContextTest test application, as shown here,
```
        return ShrinkWrap.create(WebArchive.class, ThreadContextTest.class.getSimpleName() + ".war")
                .addClass(ThreadContextTest.class)
                .addAsLibraries(threadPriorityContextProvider, multiContextProvider);
```

and therefore should have no effect on the `unchangedContextListDefaultsToEmpty` test, which is the behavior the we see when running it with our own implementation.  You might want to look into whether your implementation has a bug in how it handles microprofile-config.properties, where it is applying it from a different application or across applications.
