### ISSUE TITLE
Project still listed as microprofile-concurrency in microprofile page

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-context-propagation#168]
At https://microprofile.io/project/eclipse/microprofile-concurrency and https://microprofile.io/projects/

@kenfinnigan do you know how we can fix this?

**Comment by kenfinnigan** [comment]
I think https://github.com/microprofile/microprofile-site-config/pull/85 should fix it

**Comment by FroMage** [comment]
Thanks, let's merge it :)

**Comment by FroMage** [comment]
How much time do we have to wait for the changes to be propagated?

**Comment by kenfinnigan** [comment]
Not sure.

@rstjames, do you know how long it takes for an update here to propagate? Do we need to trigger something else?

**Comment by FroMage** [comment]
@rstjames ^^?

**Comment by kenfinnigan** [comment]
Just verified this is now fixed on the website
