### ISSUE TITLE
Release note updates missed for 1.1

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-context-propagation#204]
Updates to the release notes were missed for release 1.1.  John Clingan pointed out in the post where he notified us of this that we can still go back and include this information so that it will be there when a new release is created.

**Comment by Emily-Jiang** [comment]
@njr-11 please follow the [instruction](https://wiki.eclipse.org/MicroProfile/SpecRelease/Release#New_release_process) for release notes . The 2nd step clearly documents how to write the release note.
