### ISSUE TITLE
Release Context Propagation 1.2

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-context-propagation#206]
Since Context Propagation 1.1 was released bypassing EF rules, the spec pdf/html, javadoc licenses need to be fixed. See PR example [here](https://github.com/eclipse/microprofile-rest-client/pull/292). A proper review process needs to be engaged. The release [wiki](https://wiki.eclipse.org/MicroProfile/SpecRelease/Release) has the detailed instructions on how to release.

After some [discussion](https://groups.google.com/g/microprofile/c/Ewga0Ix1Gdo) on the google group, the consensus is that Context Propagation 1.2 needs to be released to supercede 1.1. 

The spec change notes need to reflect this.

**Comment by njr-11** [comment]
MicroProfile Context Propagation 1.2 has been released:
https://github.com/eclipse/microprofile-context-propagation/releases/tag/1.2
