### ISSUE TITLE
MicroProfile Context Propagation 1.2 Compatible Certification Request

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-context-propagation#209]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  IBM
  <br/>
- [x] Product Name, Version and download URL (if applicable):<br/>
  Open Liberty 21.0.0.3-beta (publicly released image using the official MP Context Propagation 1.2 RC1 from maven) - [210220210209-1100](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/tck/2021-02-09_1100/openliberty-21.0.0.3-beta.zip) at commit [dbac5467f2e6e80c6ec9abaea5cf0165e30b0d60](https://github.com/OpenLiberty/open-liberty/commit/dbac5467f2e6e80c6ec9abaea5cf0165e30b0d60)
  Open Liberty TCK build (using MP Context Propagation 1.2 final from staging) - [202102051432-1214](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/tck/2021-02-05_1432/openliberty-all-21.0.0.2-202102051432-1214.zip)
  <br/>
- [x] Specification Name, Version and download URL:<br/>
  [MicroProfile Context Propagation 1.2 spec HTML - staging location](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1434/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-spec/1.2/microprofile-context-propagation-spec-1.2.html)
  [MicroProfile Context Propagation 1.2 spec PDF - staging location](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1434/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-spec/1.2/microprofile-context-propagation-spec-1.2.pdf)
  [MicroProfile Context Propagation 1.2 API jar - staging location](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1434/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-api/1.2/microprofile-context-propagation-api-1.2.jar)
  [MicroProfile Context Propagation 1.2 spec HTML - future location once released](https://download.eclipse.org/microprofile/microprofile-context-propagation-1.2/microprofile-context-propagation-spec-1.2.html)
  [MicroProfile Context Propagation 1.2 spec PDF - future location once released](https://download.eclipse.org/microprofile/microprofile-context-propagation-1.2/microprofile-context-propagation-spec-1.2.pdf)
  [MicroProfile Context Propagation 1.2 API jar - future location once released](https://repo1.maven.org/maven2/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-api/1.2/microprofile-context-propagation-api-1.2.jar)
  <br/>
- [x] (Optional) TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [MicroProfile Context Propagation 1.2 RC1 TCK](https://repo1.maven.org/maven2/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-tck/1.2-RC1/microprofile-context-propagation-tck-1.2-RC1.jar)
  [MicroProfile Context Propagation 1.2 TCK - staging location](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1434/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-tck/1.2/)
  [MicroProfile Context Propagation 1.2 TCK - future location once released](https://repo1.maven.org/maven2/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-tck/1.2/microprofile-context-propagation-tck-1.2.jar)
  <br/>
- [x] Public URL of TCK Results Summary:<br/>
  [https://openliberty.io/certifications/microprofile/contextpropagation/1.2/TCKResults.html](https://openliberty.io/certifications/microprofile/contextpropagation/1.2/TCKResults.html) This contains results for both the official 1.2 RC1 as well as the staged final 1.2 that is otherwise identical to 1.2 RC1 but not released yet.
  <br/>
- [x] Any Additional Specification Certification Requirements:<br/>
  None
  <br/>
- [x] Java runtime used to run the implementation:<br/>
  For official 1.2 RC1:
  Java 8: `OpenJDK Runtime Environment (1.8.0_282-b08)`
  Java 11: `OpenJDK Runtime Environment (11.0.2+9)`<br/>
  For staged final 1.2:
  Java 8: `OpenJDK Runtime Environment (1.8.0_252-b09)`
  Java 11: `OpenJDK Runtime Environment (11.0.7+10)`
  <br/>
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  For official 1.2 RC1:
  Java 8 TCK run: `Mac OS X (10.15.7; x86_64) (en_US)`
  Java 11 TCK run: `Mac OS X (10.15.7; amd64) (en_US)`<br/>
  For staged final 1.2:
  Java 8 TCK run: `Linux (4.18.0-147.8.1.el8_1.x86_64; amd64) (en_US)`
  Java 11 TCK run: `Linux (4.15.0-20-generic; amd64) (en_US)`
  <br/>
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

Here is an explanation of why there are two different sets of TCK runs documented above.
There is an ongoing discussion on the MicroProfile mailing list to improve this process for certifying https://groups.google.com/g/microprofile/c/6v65mBjIXiQ/m/zxoSUhlyAgAJ which will address the problem that some compatible implementations will not permit releasing an official GA/beta version based on staging artifacts.  The only way to get an official released version of the compatible implementation is to use artifacts that are actually on maven, MP Context Propagation 1.2 RC1, which is identical to the 1.2 final version on staging except that it's marked release candidate rather than final.  I also included TCK runs with the final version from staging, but because it's on staging, we can only get a development build of the compatible implementation with the staged artifacts.  The TCK passes fully on both.  Now to add even more complexity to this, the original final build on staging disappeared.  Possibly because we took too long and didn't release it in time?  In any case, I resubmitted it and it created another copy of the artifacts on staging.  Links above are updated so that they are no longer broken -- at least for now.  Hopefully we can get this one released before it goes away like the other did.

**Comment by Emily-Jiang** [comment]
The link to Specification Name, Version and download URL: is the staged repo, which will be broken once the release is pushed to maven. In the previous MP 4.0, @kwsutter askedto use the maven central to be existed link. See [here](https://github.com/eclipse/microprofile-open-api/issues/459). Both of the links are not ideal. I asked this question on MP googlegroup mail and wait for people to share their ideas.

**Comment by njr-11** [comment]
> The link to Specification Name, Version and download URL: is the staged repo, which will be broken once the release is pushed to maven. In the previous MP 4.0, @kwsutter askedto use the maven central to be existed link. See [here](https://github.com/eclipse/microprofile-open-api/issues/459). Both of the links are not ideal. I asked this question on MP googlegroup mail and wait for people to share their ideas.

@Emily-Jiang I updated it to include both the current location (staging) and future location after released (Maven central).

**Comment by kwsutter** [comment]
The links in the "Specification Name, Version and download URL:" section all seem to be pointing at the APIs.  Shouldn't these be pointing at the Specification?  Something like this:  https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1434/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-spec/1.2/

**Comment by njr-11** [comment]
> The links in the "Specification Name, Version and download URL:" section all seem to be pointing at the APIs. Shouldn't these be pointing at the Specification? Something like this: https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1434/org/eclipse/microprofile/context-propagation/microprofile-context-propagation-spec/1.2/

Sorry, I misunderstood the intent of this section. It is updated now to point to the actual spec doc at those locations. I left the link to the API jar in there as well. Let me know if you wanted that removed, too.
